#!/usr/bin/env bash
# print best school 10 tiems

# initialize counter
count=0

# loop while counter is less than 10
while [ $count -lt 10 ]
do
  echo "Best School"
  # increment counter
  ((count++))
done
